import {
  CarTransmissionIcon,
  CarEngineIcon,
  CarIcon,
  CarCleanerIcon,
  CarWheelIcon,
  CarDisksIcon,
  CarWheelsIcon,
  CarDiagnosticIcon,
  CarOilIcon,
  CarGearboxIcon,
  CarRoleIcon,
} from "../../../../customIcons";
import { CarGasolineIcon } from "../../../../customIcons/car-section/CarGasolineIcon";

export const paths = [
  {
    id: 1,
    img: <CarDiagnosticIcon width={116} heigth={116} color="#fff" />,
    title: "Диагностика",
    description: "ОТ 32 РУБЛЕЙ",
    button: "Записаться",
  },
  {
    id: 2,
    img: <CarEngineIcon width={116} heigth={116} color="#fff" />,
    title: "РЕМОНТ ДВИГАТЕЛЯ",
    description: "ОТ 32 РУБЛЕЙ",
    button: "Записаться",
  },
  {
    id: 3,
    img: <CarWheelsIcon width={116} heigth={116} color="#fff" />,
    title: "ШИНОМОНТАЖ",
    description: "ОТ 32 РУБЛЕЙ",
    button: "Записаться",
  },
  {
    id: 4,
    img: <CarDisksIcon width={116} heigth={116} color="#fff" />,
    title: "ЗАМЕНА КОЛОДОК",
    description: "ОТ 32 РУБЛЕЙ",
    button: "Записаться",
  },
  {
    id: 5,
    img: <CarTransmissionIcon width={116} heigth={116} color="#fff" />,
    title: "РЕМОНТ ТРАНСМИССИИ",
    description: "ОТ 32 РУБЛЕЙ",
    button: "Записаться",
  },
  {
    id: 6,
    img: <CarIcon width={116} heigth={116} color="#fff" />,
    title: "КУЗОВНОЙ РЕМОНТ",
    description: "ОТ 32 РУБЛЕЙ",
    button: "Записаться",
  },
  {
    id: 7,
    img: <CarWheelIcon width={116} heigth={116} color="#fff" />,
    title: "СХОД/РАЗВАЛ",
    description: "ОТ 32 РУБЛЕЙ",
    button: "Записаться",
  },
  {
    id: 8,
    img: <CarCleanerIcon width={116} heigth={116} color="#fff" />,
    title: "ХИМЧИСТКА САЛОНА",
    description: "ОТ 32 РУБЛЕЙ",
    button: "Записаться",
  },
  {
    id: 9,
    img: <CarOilIcon width={116} heigth={116} color="#fff" />,
    title: "ЗАМЕНА МАСЛА",
    description: "ОТ 32 РУБЛЕЙ",
    button: "Записаться",
  },
  {
    id: 10,
    img: <CarGearboxIcon width={116} heigth={116} color="#fff" />,
    title: "РЕМОНТ АКПП",
    description: "ОТ 32 РУБЛЕЙ",
    button: "Записаться",
  },
  {
    id: 11,
    img: <CarRoleIcon width={116} heigth={116} color="#fff" />,
    title: "РУЛЕВОЕ УПРАВЛЕНИЕ",
    description: "ОТ 32 РУБЛЕЙ",
    button: "Записаться",
  },
  {
    id: 12,
    img: <CarGasolineIcon width={116} heigth={116} color="#fff" />,
    title: "ТОПЛИВНАЯ СИСТЕМА",
    description: "ОТ 32 РУБЛЕЙ",
    button: "Записаться",
  },
];
